#!/usr/bin/env bash
# This script configures the local host file to change IP addresses.

# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Change localhost IP to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Change facebook.com IP to 8.8.8.8
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts

# Display the modified /etc/hosts file
cat /etc/hosts

